# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    assets:
        packages:
            css:
                base_path: packages/css/
            fonts:
                base_path: packages/fonts/
            images:
                base_path: packages/images/
            js:
                base_path: packages/js/
            scss:
                base_path: packages/scss/
            vendors:
                base_path: packages/vendors/

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
